### ISSUE TITLE
Flaky: Target.createTarget

### ISSUE THREAD

**Issue by YusukeIwaki** [YusukeIwaki/puppeteer-ruby#91]
### Step To Reproduce / Observed behavior

Call `Browser#new_page`.

Sometimes it fails:

```
Failures:

  1) Puppeteer::Page BrowserContext#override_permissions should fail when bad permission is given
     Failure/Error: await target.initialized_promise
     
     NoMethodError:
       undefined method `initialized_promise' for nil:NilClass
     # ./lib/puppeteer/browser.rb:187:in `create_page_in_context'
     # ./lib/puppeteer/browser_context.rb:105:in `new_page'
```
